"""add whatsapp to site_info

Revision ID: 0b1256dc2860
Revises: 1b48f06f23a7
Create Date: 2025-11-13 17:22:00.114053

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b1256dc2860'
down_revision = '1b48f06f23a7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('whatsapp', sa.String(length=80), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('site_info', schema=None) as batch_op:
        batch_op.drop_column('whatsapp')

    # ### end Alembic commands ###
