"""add site_info table

Revision ID: 1b48f06f23a7
Revises: 20aa93ac6bcb
Create Date: 2025-11-13 17:12:43.455432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b48f06f23a7'
down_revision = '20aa93ac6bcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('site_info',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('store_name', sa.String(length=160), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=False),
    sa.Column('hours', sa.String(length=400), nullable=False),
    sa.Column('email', sa.String(length=160), nullable=True),
    sa.Column('phone', sa.String(length=80), nullable=True),
    sa.Column('instagram', sa.String(length=160), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('site_info')
    # ### end Alembic commands ###
