"""add product image_filename

Revision ID: 20aa93ac6bcb
Revises: 1480436a719b
Create Date: 2025-11-13 16:49:12.648704

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '20aa93ac6bcb'
down_revision = '1480436a719b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image_filename', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('image_filename')

    # ### end Alembic commands ###
