"""add featured to products

Revision ID: a1f2c3d4e5f6
Revises: e763cb475c9c
Create Date: 2025-11-13 18:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a1f2c3d4e5f6'
down_revision = 'e763cb475c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('featured', sa.Boolean(), nullable=False, server_default=sa.text('false')))
        batch_op.create_index('ix_products_featured', ['featured'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index('ix_products_featured')
        batch_op.drop_column('featured')

    # ### end Alembic commands ###
