"""add slides table

Revision ID: e763cb475c9c
Revises: 0b1256dc2860
Create Date: 2025-11-13 17:47:06.062151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e763cb475c9c'
down_revision = '0b1256dc2860'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('slides',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_filename', sa.String(length=200), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('slides')
    # ### end Alembic commands ###
